apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: ru.yandex.s3.csi
    volume.kubernetes.io/storage-provisioner: ru.yandex.s3.csi
  creationTimestamp: "2026-02-23T08:47:26Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: s3-pvc-test
  namespace: default
  resourceVersion: "5503"
  uid: e51cbe76-22f3-474b-8b96-b0fd6d3291b3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-s3
  volumeMode: Filesystem
  volumeName: pvc-e51cbe76-22f3-474b-8b96-b0fd6d3291b3
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
