apiVersion: v1
data:
  accessKeyID: secret
  endpoint: secret
  secretAccessKey: secret
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: csi-s3
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2026-02-23T08:41:28Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: csi-s3-secret
  namespace: kube-system
  resourceVersion: "3788"
  uid: 25f0c3b1-049f-4535-9177-c1ccccfc0363
type: Opaque
