global:
  nodeSelector:
    node-role: infra
  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"

server:
  nodeSelector:
    node-role: infra
  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"

repoServer:
  nodeSelector:
    node-role: infra
  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"

controller:
  nodeSelector:
    node-role: infra
  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"

dex:
  enabled: true
  nodeSelector:
    node-role: infra
  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"

redis:
  enabled: true
  nodeSelector:
    node-role: infra
  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"