apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  type: ClusterIP
  selector:
    myapp: web-server
  ports:
    - name: web-server-port
      protocol: TCP
      port: 80
      targetPort: 80