apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter-service
spec:
  type: ClusterIP
  selector:
    myapp: web-server
  ports:
    - name: nginx-exporter-port
      protocol: TCP
      port: 9113
      targetPort: 9113