apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-exporter-monitor
  labels:
    myapp: nginx-exporter-monitor
spec:
  selector:
    matchLabels:
      myapp: web-server
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: nginx-exporter-port
      path: /metrics
      interval: 15s
      scheme: http