apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.fullname }}-monitoring
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  TOKEN: {{ .Values.secret.monitoringToken | quote }}