apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.monitoring.name }}
  namespace: {{ .Values.namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.cd.name }}
  namespace: {{ .Values.namespace }}