apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: homework
data:
  key1: a
  key2: b
  key3: c
  default.conf: |
    server {
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;

    index index.php index.html index.htm;

    location / { try_files $uri $uri/ /index.php }

    location ~* .(css|js)$ { access_log off; expires max; }
    }